---
kind: architecture configuration
type: fully configured
name: kronos-rv32imc
description: kronos stage 3 - RV32IMC
implemented_extensions:
  - { name: I,        version: "= 2.1" }
  - { name: M,        version: "= 2.0" }
  - { name: C,        version: "= 2.0" }
  - { name: Zca,      version: "= 1.0.0" }
  - { name: Zicsr,    version: "= 2.0" }
  - { name: Zifencei, version: "= 2.0" }
params:
  MXLEN: 32
  MISALIGNED_AMO: false
  LRSC_RESERVATION_STRATEGY: "reserve exactly enough to cover the access"
  LRSC_FAIL_ON_VA_SYNONYM: false
  LRSC_MISALIGNED_BEHAVIOR: "always raise access fault"
  LRSC_FAIL_ON_NON_EXACT_LRSC: false
  MUTABLE_MISA_A: false
  MUTABLE_MISA_M: false
  MUTABLE_MISA_F: false
  HW_MSTATUS_FS_DIRTY_UPDATE: precise
  MSTATUS_FS_LEGAL_VALUES: [0, 1, 2, 3]
  MUTABLE_MISA_D: false
  MUTABLE_MISA_C: false
  TIME_CSR_IMPLEMENTED: true
