#ifndef RVTEST_CONFIG_H
#define RVTEST_CONFIG_H
#define RVMODEL_ACCESS_FAULT_ADDRESS 0x00000000
#define RVMODEL_PMP_GRAIN 0
#define RVMODEL_NUM_PMPS 0
#define TIME_CSR_IMPLEMENTED 1
#define ZCA_SUPPORTED
#endif
